"""portfolio: phases, tempo, activity events, inbox

Revision ID: 0e0c96d94f67
Revises: d21c33e7dfca
Create Date: 2026-09-12 18:44:33.269796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e0c96d94f67'
down_revision = 'd21c33e7dfca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('delta', sa.Integer(), server_default='0', nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_events_project_id'), ['project_id'], unique=False)

    op.create_table('inbox_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revisit_on', sa.Date(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbox_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbox_items_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phase', sa.String(length=20), server_default='idea', nullable=False))
        batch_op.add_column(sa.Column('cadence_days', sa.Integer(), server_default='14', nullable=False))
        batch_op.add_column(sa.Column('next_action', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('parked_until', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('repo_path', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True))

    # Existing projects: treat creation as the last touch, and put projects
    # that already have a tree into Building rather than Idea.
    op.execute("UPDATE projects SET last_activity_at = created_at WHERE last_activity_at IS NULL")
    op.execute("UPDATE projects SET phase = 'building' "
               "WHERE id IN (SELECT DISTINCT project_id FROM branches)")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('last_activity_at')
        batch_op.drop_column('repo_path')
        batch_op.drop_column('parked_until')
        batch_op.drop_column('next_action')
        batch_op.drop_column('cadence_days')
        batch_op.drop_column('phase')

    with op.batch_alter_table('inbox_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbox_items_user_id'))

    op.drop_table('inbox_items')
    with op.batch_alter_table('activity_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_events_project_id'))
        batch_op.drop_index(batch_op.f('ix_activity_events_created_at'))

    op.drop_table('activity_events')
    # ### end Alembic commands ###
