"""custom project templates

Revision ID: 53923e41872e
Revises: b75584e330e9
Create Date: 2026-09-12 23:18:11.333970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53923e41872e'
down_revision = 'b75584e330e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('hint', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_user_id'), ['user_id'], unique=False)

    op.create_table('template_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('hue', sa.String(length=20), server_default='green', nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    # sa.false(), not the autogenerated sa.text('0'): Postgres rejects 0 as a
    # boolean literal and production is Postgres.
    sa.Column('waits', sa.Boolean(), server_default=sa.false(), nullable=False),
    sa.Column('tasks_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('template_branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_branches_template_id'), ['template_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template_branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_branches_template_id'))

    op.drop_table('template_branches')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_user_id'))

    op.drop_table('templates')
    # ### end Alembic commands ###
