"""project objective

Revision ID: 875ff314d379
Revises: 0e0c96d94f67
Create Date: 2026-09-12 20:46:12.087736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875ff314d379'
down_revision = '0e0c96d94f67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('objective', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('objective')

    # ### end Alembic commands ###
