"""project focus flag

Revision ID: b75584e330e9
Revises: fc2fa2fa4674
Create Date: 2026-09-12 22:49:09.975497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75584e330e9'
down_revision = 'fc2fa2fa4674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # sa.true() rather than the autogenerated sa.text('1'): SQLite takes 1 for
    # a boolean, Postgres does not, and production is Postgres.
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('focused', sa.Boolean(), server_default=sa.true(), nullable=False))

    # Existing projects: what is still live starts in focus, what is already
    # shelved starts on the backburner, so the first view of the split is
    # meaningful rather than everything in one pile.
    op.execute("UPDATE projects SET focused = false "
               "WHERE phase IN ('parked', 'done', 'dropped')")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('focused')

    # ### end Alembic commands ###
