"""per-user wip building limit

Revision ID: fc2fa2fa4674
Revises: 875ff314d379
Create Date: 2026-09-12 21:12:39.843242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc2fa2fa4674'
down_revision = '875ff314d379'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wip_building_limit', sa.Integer(), server_default='3', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('wip_building_limit')

    # ### end Alembic commands ###
